### ISSUE TITLE
Colocar um README.md para organizar seu repositório

### ISSUE THREAD

**Issue by bpires** [Hersonmei/Explorer#1]
Fala Herson!

Tou vendo que você tá reunindo todos seus projetos nessa pasta e já fez o deploy deles :clap: muito massa!

Ficou faltando você colocar um README.md no repositório principal, falando um pouco sobre o propósito do repositório e de preferência com os links para os subrepositórios, se não fica difícil de ver teus projetos on line.

Cada subrepositório também pode ter um README.md com informações mais detalhadas.  

Aqui um exemplo básico para você usar como ponto de partida para o teu:

```
# Meus projetos

![last commit](https://img.shields.io/github/last-commit/Hersonmei/Explorer?color=2c5a6c 'last commit') &nbsp; ![repo size](https://img.shields.io/github/repo-size/Hersonmei/Explorer?color=2c5a6c 'repo size') &nbsp; ![languages](https://img.shields.io/github/languages/count/Hersonmei/Explorer?color=2c5a6c 'languages')
---

### 📌 Índice

#### Nível 2
- Desafio - Fase 01: [resultado final](https://hersonmei.github.io/Explorer/Nivel%202/Desafio%20-%20Fase%2001/) | [repositório](https://github.com/Hersonmei/Explorer/tree/main/Nivel%202/Desafio%20-%20Fase%2001)
- Desafio - Fase 02 Intermediário: [resultado final](https://hersonmei.github.io/Explorer/Nivel%202/Desafio%20-%20Fase%2002%20Intermediário/) | [repositório](https://github.com/Hersonmei/Explorer/tree/main/Nivel%202/Desafio%20-%20Fase%2002%20Intermediário/)
.
.
.
.
.
etc.
```

Copia e cola em um arquivo README.md, testa e vai adaptando!

Vê como eu fiz aqui: [bpires/rocketseat-explorer/](https://github.com/bpires/rocketseat-explorer) (usei um repositório só para todos os projetos) ou nesse excelente [repo do Felipe Vicente](https://github.com/felipe-gomes-vicente/rocket-sect) (já ele tem guardado os projetos feitos na aula em um repositório só, porém tem dado destaque aos desafios em repositórios próprios).

E se você quiser algumas ideias de como deixar teus repositórios e perfil do GitHub mais amigáveis, dá uma conferida também nesse site que meu irmão fez: https://readmecreator.herokuapp.com/

Dá para você pegar algumas boas ideias e deixar com a sua cara depois!

Abs!

**Comment by Hersonmei** [comment]
Eita Rafel, que isso hein cara? =D

Valeu demais mesmo irmão!! Ficou simples esse modelo mas muito legal mesmo, do jeito que gosto de deixar as coisas. Vou só terminar de completar esse e depois colocar o README.md dentro de cada projeto como modelo do seu irmão. Obrigado mesmo!!

**Comment by bpires** [comment]
Tamo junto, só vai 🚀
